server:
  port: 8095
spring:
  application:
    name: coffee-auth
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        file-extension: yaml
        namespace: d025a889-46b6-43b1-97ae-27daf2b5ad91
        group: MODULES_GROUP

  config:
    import:
      - optional:nacos:knife4j-boot.yaml?group=DEFAULT_GROUP
      - optional:nacos:redis.yaml?group=DATASOURCE_GROUP
      - optional:nacos:coffee-auth.yaml?group=DEFAULT_GROUP
      - optional:nacos:logback-spring.xml?group=DEFAULT_GROUP

#  profiles:
#    active: dev
